OUTPUT_DIR: "./exp_cuhk"
INPUT:
  DATASET: "cuhk_sysu"
  #DATA_ROOT: "data/CUHK-SYSU" #For local PC
  DATA_ROOT: "kaggle/input/cuhk-sysu/cuhk_sysu" #For Kaggle
SOLVER:
  MAX_EPOCHS: 20
MODEL:
  LOSS:
    LUT_SIZE: 5532
    CQ_SIZE: 5000