OUTPUT_DIR: "./exp_prw"
INPUT:
  DATASET: "prw"
  #DATA_ROOT: "data/PRW" #For local PC
  DATA_ROOT: "kaggle/input/prw-personsearch/prw" #For Kaggle
SOLVER:
  MAX_EPOCHS: 18
MODEL:
  LOSS:
    LUT_SIZE: 482
    CQ_SIZE: 500